from enum import Enum


class EventType(str, Enum):

    # Products
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    # Inventory
    STOCK_RECEIVED = "STOCK_RECEIVED"
    STOCK_DEDUCTED = "STOCK_DEDUCTED"

    # Sales
    SALE_CREATED = "SALE_CREATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"

    # Customers
    CUSTOMER_CREATED = "CUSTOMER_CREATED"

    # Debts
    DEBT_CREATED = "DEBT_CREATED"
    DEBT_SETTLED = "DEBT_SETTLED"

    # Expenses
    EXPENSE_RECORDED = "EXPENSE_RECORDED"

    # Suppliers
    SUPPLIER_CREATED = "SUPPLIER_CREATED"
    PURCHASE_RECORDED = "PURCHASE_RECORDED"

    # Branches
    BRANCH_CREATED = "BRANCH_CREATED"
    BRANCH_UPDATED = "BRANCH_UPDATED"

    # Users
    USER_CREATED = "USER_CREATED"

    # login
    LOGIN_RECORDED = "LOGIN_RECORDED"

    BRANCH_TRANSFER_CREATED = (
    "BRANCH_TRANSFER_CREATED"
)

BRANCH_TRANSFER_SETTLED = (
    "BRANCH_TRANSFER_SETTLED"
)