from enum import Enum


class EventType(str, Enum):

    # Products
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    # Inventory
    INVENTORY_RECEIVED = "INVENTORY_RECEIVED"
    INVENTORY_DEDUCTED = "INVENTORY_DEDUCTED"
    INVENTORY_ADJUSTED = "INVENTORY_ADJUSTED"

    # Sales
    SALE_CREATED = "SALE_CREATED"
    SALE_LINE_ADDED = "SALE_LINE_ADDED"
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_CANCELLED = "SALE_CANCELLED"

    # Payments
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_CANCELLED = "PAYMENT_CANCELLED"

    # Customers
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"

    # Receivables
    RECEIVABLE_CREATED = "RECEIVABLE_CREATED"
    RECEIVABLE_PAYMENT_RECORDED = "RECEIVABLE_PAYMENT_RECORDED"
    RECEIVABLE_SETTLED = "RECEIVABLE_SETTLED"

    # Expenses
    EXPENSE_CREATED = "EXPENSE_CREATED"
    EXPENSE_APPROVED = "EXPENSE_APPROVED"
    EXPENSE_PAID = "EXPENSE_PAID"

    # Suppliers
    SUPPLIER_CREATED = "SUPPLIER_CREATED"
    SUPPLIER_UPDATED = "SUPPLIER_UPDATED"

    # Purchases
    PURCHASE_CREATED = "PURCHASE_CREATED"
    PURCHASE_RECEIVED = "PURCHASE_RECEIVED"
    PURCHASE_CANCELLED = "PURCHASE_CANCELLED"

    # Payables
    PAYABLE_CREATED = "PAYABLE_CREATED"
    PAYABLE_PAYMENT_RECORDED = "PAYABLE_PAYMENT_RECORDED"
    PAYABLE_SETTLED = "PAYABLE_SETTLED"

    # Branches
    BRANCH_CREATED = "BRANCH_CREATED"
    BRANCH_UPDATED = "BRANCH_UPDATED"

    # Transfers
    BRANCH_TRANSFER_CREATED = "BRANCH_TRANSFER_CREATED"
    BRANCH_TRANSFER_SETTLED = "BRANCH_TRANSFER_SETTLED"
    BRANCH_TRANSFER_CANCELLED = "BRANCH_TRANSFER_CANCELLED"

    # Users
    USER_CREATED = "USER_CREATED"
    LOGIN_RECORDED = "LOGIN_RECORDED"