from enum import Enum


class EventType(str, Enum):

    # Products
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    # Inventory
    INVENTORY_RECEIVED = "INVENTORY_RECEIVED"
    INVENTORY_DEDUCTED = "INVENTORY_DEDUCTED"
    INVENTORY_ADJUSTED = "INVENTORY_ADJUSTED"

    # Sales
    SALE_CREATED = "SALE_CREATED"
    SALE_LINE_ADDED = "SALE_LINE_ADDED"
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_CANCELLED = "SALE_CANCELLED"

    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"

    # Customers
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"

    # Debts
    DEBT_CREATED = "DEBT_CREATED"
    DEBT_PAYMENT_RECEIVED = "DEBT_PAYMENT_RECEIVED"
    DEBT_SETTLED = "DEBT_SETTLED"

    # Expenses
    EXPENSE_RECORDED = "EXPENSE_RECORDED"

    # Suppliers
    SUPPLIER_CREATED = "SUPPLIER_CREATED"
    PURCHASE_ORDER_CREATED = "PURCHASE_ORDER_CREATED"
    PURCHASE_RECEIVED = "PURCHASE_RECEIVED"

    # Branches
    BRANCH_CREATED = "BRANCH_CREATED"
    BRANCH_UPDATED = "BRANCH_UPDATED"

    # Transfers
    BRANCH_TRANSFER_CREATED = "BRANCH_TRANSFER_CREATED"
    BRANCH_TRANSFER_SETTLED = "BRANCH_TRANSFER_SETTLED"
    BRANCH_TRANSFER_CANCELLED = "BRANCH_TRANSFER_CANCELLED"

    # Users
    USER_CREATED = "USER_CREATED"
    LOGIN_RECORDED = "LOGIN_RECORDED"